apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-provisioning
    files:
      - config/grafana/provisioning/datasources/datasources.yml
      - config/grafana/provisioning/alerting/alerts.yml
      - config/grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-dashboards
    files:
      - config/grafana/dashboards/otel_mvp.json
  - name: loki-config
    files:
      - config/loki/loki-config.yml
  - name: tempo-config
    files:
      - config/tempo/tempo-config.yml
  - name: prometheus-config
    files:
      - config/prometheus/prometheus.yml
  - name: otelcol-config
    files:
      - config/otel-collector/otelcol-config.yml

secretGenerator:
  - name: grafana-admin
    literals:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

resources:
  - namespace.yaml
  - grafana.yaml
  - loki.yaml
  - tempo.yaml
  - prometheus.yaml
  - otelcol.yaml
  - space-app.yaml
  - loadgen.yaml
