apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/part-of: otel-lgtm-mvp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
        app.kubernetes.io/part-of: otel-lgtm-mvp
    spec:
      containers:
        - name: otelcol
          image: otel/opentelemetry-collector-contrib:0.133.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config=/etc/otelcol/otelcol-config.yml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 8889
              name: metrics
          volumeMounts:
            - name: otelcol-config
              mountPath: /etc/otelcol
              readOnly: true
      volumes:
        - name: otelcol-config
          configMap:
            name: otelcol-config
---
apiVersion: v1
kind: Service
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  selector:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/part-of: otel-lgtm-mvp
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: metrics
      port: 8889
      targetPort: metrics
