apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-app
  labels:
    app.kubernetes.io/name: space-app
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: space-app
      app.kubernetes.io/part-of: otel-lgtm-mvp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: space-app
        app.kubernetes.io/part-of: otel-lgtm-mvp
    spec:
      containers:
        - name: space-app
          image: ghcr.io/hyzhak/otel-lgtm-mvp/space-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: OTEL_SERVICE_NAME
              value: space-app
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=1.0.0,service.namespace=demo,service.instance.id=$(POD_NAME)
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol:4318
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: space-app
  labels:
    app.kubernetes.io/name: space-app
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: space-app
    app.kubernetes.io/part-of: otel-lgtm-mvp
  ports:
    - name: http
      port: 8000
      targetPort: http
