apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/part-of: otel-lgtm-mvp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
        app.kubernetes.io/part-of: otel-lgtm-mvp
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.8.2
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/tempo/config/tempo-config.yml"
          ports:
            - containerPort: 3200
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo/config
              readOnly: true
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-data
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: otel-lgtm-mvp
  ports:
    - name: http
      port: 3200
      targetPort: http
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
