# Minimal single-binary Loki 3.x for local filesystem storage + TSDB index

auth_enabled: false 

common:
  path_prefix: /loki  # satisfies TSDB index requirements

server:
  http_listen_port: 3100
  grpc_listen_port: 0

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  # NOTE: removed: max_transfer_retries (deprecated/invalid)

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    # NOTE: do not set shared_store here; not needed for filesystem

limits_config:
  allow_structured_metadata: true
  volume_enabled: true      # 👈 required for Log Volume UI to work

compactor:
  working_directory: /loki/compactor
  # NOTE: removed: shared_store (deprecated/invalid)
  compactor_ring:
    kvstore:
      store: inmemory
