server:
  http_listen_port: 3100
  grpc_listen_port: 0

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  # NOTE: removed: max_transfer_retries (invalid in this version)

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: true

compactor:
  working_directory: /loki/compactor
  # NOTE: removed: shared_store (invalid in this version)
  compactor_ring:
    kvstore:
      store: inmemory
