apiVersion: 1

contactPoints:
  - orgId: 1
    name: console
    receivers:
      - uid: console
        type: webhook
        settings:
          url: http://localhost:65535/nowhere

policies:
  - orgId: 1
    receiver: console

rules:
  - orgId: 1
    name: High error rate (space-app)
    folder: Alerts
    interval: 30s
    condition: B
    data:
      - refId: A
        datasourceUid: prometheus
        relativeTimeRange:
          from: 600
          to: 0
        model:
          expr: sum(rate(app_request_errors_total[1m]))
          interval: ""
          legendFormat: "errors/s"
          refId: A
      - refId: B
        datasourceUid: __expr__
        model:
          type: threshold
          expression: A
          conditions:
            - evaluator:
                params: [0.0167]
                type: gt
              operator:
                type: and
              reducer:
                type: last
              type: query
    for: 2m
    annotations:
      summary: "Error rate >= 1/min over 2m"
      description: "space-app is erroring. Check /error endpoint & logs."