apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patches/storage-class.yaml
  - path: patches/grafana-service.yaml
  - path: patches/resource-limits.yaml
