apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app.kubernetes.io/name: loadgen
    app.kubernetes.io/part-of: otel-lgtm-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgen
      app.kubernetes.io/part-of: otel-lgtm-mvp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadgen
        app.kubernetes.io/part-of: otel-lgtm-mvp
    spec:
      containers:
        - name: loadgen
          image: ghcr.io/hyzhak/otel-lgtm-mvp/loadgen:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET_BASE_URL
              value: http://space-app:8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
