name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment variables for CI
        run: |
          if [ ! -f .env ] && [ -f .env.example ]; then
            cp .env.example .env
          fi
      - name: Run integration tests via docker compose
        run: |
          set -euo pipefail
          status=0
          docker compose -f docker-compose.yml -f docker-compose.integration.yml up --build --exit-code-from integration-tests integration-tests || status=$?
          docker compose -f docker-compose.yml -f docker-compose.integration.yml down -v
          exit $status

  k8s-smoke:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          wait: 120s
          cluster_name: otel-lgtm

      - name: Build demo images for local overlay
        run: |
          docker build -t space-app:latest app
          docker build -t loadgen:latest loadgen
          kind load docker-image space-app:latest --name otel-lgtm
          kind load docker-image loadgen:latest --name otel-lgtm

      - name: Deploy observability stack to kind
        run: |
          kubectl kustomize k8s/base >/dev/null
          kubectl kustomize k8s/overlays/local >/dev/null
          kubectl apply -k k8s/overlays/local

      - name: Wait for deployments to become ready
        run: |
          kubectl wait --namespace observability --for=condition=Available deployment --all --timeout=5m

      - name: Smoke test FastAPI service
        run: |
          set -euo pipefail
          kubectl run curl --namespace observability --restart=Never --image=curlimages/curl:8.5.0 --command -- curl -fsS http://space-app:8000/ || {
            kubectl logs --namespace observability deploy/space-app || true
            kubectl logs --namespace observability deploy/otelcol || true
            exit 1
          }
          kubectl delete pod curl --namespace observability --wait=true

      - name: Collect diagnostics on failure
        if: failure()
        run: |
          kubectl get pods -n observability
          kubectl describe pods -n observability
          kubectl logs -n observability deploy/otelcol

      - name: Tear down stack
        if: always()
        run: |
          kubectl delete -k k8s/overlays/local
