name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment variables for CI
        run: |
          if [ ! -f .env ] && [ -f .env.example ]; then
            cp .env.example .env
          fi
      - name: Run integration tests via docker compose
        run: |
          set -euo pipefail
          status=0
          docker compose -f docker-compose.yml -f docker-compose.integration.yml up --build --exit-code-from integration-tests integration-tests || status=$?
          docker compose -f docker-compose.yml -f docker-compose.integration.yml down -v
          exit $status

  k8s-integration:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          wait: 120s
          cluster_name: otel-lgtm

      - name: Build demo images for local overlay
        run: |
          docker build -t localhost/space-app:latest app
          docker build -t localhost/loadgen:latest loadgen
          kind load docker-image localhost/space-app:latest --name otel-lgtm
          kind load docker-image localhost/loadgen:latest --name otel-lgtm

      - name: Build integration test image
        run: |
          docker build -t localhost/integration-tests:latest -f tests/integration/Dockerfile .
          kind load docker-image localhost/integration-tests:latest --name otel-lgtm

      - name: Deploy observability stack to kind
        run: |
          kubectl kustomize deploy/k8s/base >/dev/null
          kubectl kustomize deploy/k8s/overlays/local >/dev/null
          kubectl apply -k deploy/k8s/overlays/local

      - name: Wait for deployments to become ready
        run: |
          kubectl wait --namespace observability --for=condition=Available deployment --all --timeout=5m

      - name: Run Kubernetes integration tests
        run: |
          set -euo pipefail
          WAIT_TIMEOUT=15m ./scripts/run_k8s_integration_tests.sh

      - name: Collect diagnostics on failure
        if: failure()
        run: |
          kubectl get pods -n observability
          kubectl describe pods -n observability
          kubectl logs -n observability deploy/otelcol || true
          kubectl logs -n observability job/integration-tests || true

      - name: Tear down stack
        if: always()
        run: |
          kubectl delete -k deploy/k8s/overlays/local
